# -*- mode: ruby -*-
# vi: set ft=ruby :

# 设置虚拟机配置，包括hostname，ip，内存，CPU等
boxes = [
    {
        :name => "master1",
        :eth1 => "192.168.205.10",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "slave1",
        :eth1 => "192.168.205.11",
        :mem => "1024",
        :cpu => "1"
    },
    {
        :name => "slave2",
        :eth1 => "192.168.205.12",
        :mem => "1024",
        :cpu => "1"
    }
]

Vagrant.configure("2") do |config|
  # box名称
  config.vm.box = "centos/7"

  # 循环设置每台虚拟机
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      # 配置 hostname
      config.vm.hostname = opts[:name]

      # 配置内存和CPU
      config.vm.provider "virtualbox" do |v|
        v.customize ["modifyvm", :id, "--memory", opts[:mem]]
        v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
      end

      # 配置 IP
      config.vm.network :private_network, ip: opts[:eth1]
      
      # 设置网络代理(需要安装 vagrant-proxyconf 插件)
      if Vagrant.has_plugin?("vagrant-proxyconf")
        config.proxy.http     = "http://192.168.205.1:1087/"
        config.proxy.https    = "http://192.168.205.1:1087/"
        config.proxy.no_proxy = "localhost,127.0.0.1"
      end

      # 设置启动后初始化脚本，注意 privileged: true，表示以 sudo 方式运行
      config.vm.provision "shell", privileged: true, path: "./setup.sh"
      
      # 设置宿主机共享文件夹(需要安装 vagrant-vbguest 插件)
      # config.vm.synced_folder "../data", "/vagrant_data"
    end
  end

end
